# Generated by Django 3.2.19 on 2023-10-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nw_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritealbum',
            options={'ordering': ['created_on']},
        ),
    ]
