# Generated by Django 3.2.19 on 2023-06-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_blog', '0002_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
