# Generated by Django 3.2.19 on 2023-06-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_blog', '0003_rename_pickfavoritealbum_favouritealbum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritealbum',
            name='album_title',
            field=models.CharField(max_length=80),
        ),
    ]
